FROM ubuntu:latest
MAINTAINER Lokesh Kumar <lokesh904@gmail.com>

RUN \
  apt-get update && \
  apt-get -y install \
          maven && \
  rm -rf /var/lib/apt/lists/*
RUN groupadd -r admin && useradd -r -g admin admin
USER admin
