FROM ubuntu:latest
MAINTAINER Lokesh Kumar <lokesh904@gmail.com>

RUN apt update
RUN apt install -y apache2
RUN apt install -y apache2-utils
RUN apt clean
EXPOSE 80
CMD [“apache2ctl”, “-D”, “FOREGROUND”]
